server:
  port: 8005

  #eureka配置
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/

#ribbon:
#  eager-load:
#    enabled: true
feign:
  hystrix:
    enabled: true
#    clients: client1