spring:
  application:
    name: block-eureka

server:
  port: 8001
eureka:
  instance:
    hostname: server1
  client:
    #表示是否从Eureka server中获取注册信息，默认true
    fetch-registry: false
    #表示是否将自己注册到Eureka server，默认是true
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

